version: '2'
networks:
  mynetwork:
    driver: bridge
services:
  ocelot:
    build: 
      context: ./OcelotGateway
      dockerfile: Dockerfile
    ports:
      - "7001:80"
    networks:
      - mynetwork
  productapi:
    build: 
      context: ./WebAPI.Product
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - mynetwork
  cartapi:
    build: 
      context: ./WebAPI.Cart
      dockerfile: Dockerfile
    ports:
      - "6001:80"
    networks:
      - mynetwork
  seq:
    image: datalust/seq:latest  
    ports:
      - "8080:80" 
    networks:
      - mynetwork
    environment:
      ACCEPT_EULA: "Y"